services:
  - type: web
    name: sgod-mis
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt; python manage.py collectstatic --noinput
    postDeployCommand: python manage.py migrate --noinput
    startCommand: gunicorn sgod_mis.wsgi:application
    autoDeploy: false
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sgod_mis.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "sgod-mis.onrender.com"
      # Uncomment and add a Render PostgreSQL database, then set DATABASE_URL automatically
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: sgod-postgres
      #     property: connectionString
